export enum ErrorCode {
  INTERNAL_ERROR = "INTERNAL_ERROR",
  INVALID_ACCOUNT = "INVALID_ACCOUNT",
  INVALID_NONCE = "INVALID_NONCE",
  INVALID_SIGNATURE = "INVALID_SIGNATURE",
  INVALID_TWEET_URL = "INVALID_TWEET_URL",
  USER_ID_CLAIMED = "USER_ID_CLAIMED",
  CLAIM_EXPIRED = "CLAIM_EXPIRED",
}
